apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customservices.sample.javaoperatorsdk
spec:
  group: sample.javaoperatorsdk
  scope: Namespaced
  names:
    plural: customservices
    singular: customservice
    kind: CustomService
    shortNames:
      - cs
  versions:
    - name: v1
      served: true
      storage: true